import type { To } from "react-router-dom";
import type { Location } from "react-router-dom";

/**
 * Represents a single open tab in the MultiTabs component.
 */
export interface MultiTabItem {
  /** Unique stable ID derived from route path + params */
  id: string;
  /** Display title shown in the tab */
  title: string;
  /** Icon identifier string. Null hides the icon slot. */
  icon: string | null;
  /** React Router navigation target */
  to: To;
  /** Route pathname */
  routePath?: string | null;
  /** Optional consumer metadata for custom integrations */
  metadata?: Record<string, unknown>;
}

/**
 * Theme configuration for the MultiTabs component.
 */
export interface MultiTabsTheme {
  height?: string;
  shellBg?: string;
  tabBg?: string;
  tabColor?: string;
  activeTabBg?: string;
  activeTabColor?: string;
  activeTabBorderColor?: string;
  borderRadius?: string;
  fontSize?: string;
  tabMaxWidth?: string;
  tabMinWidth?: string;
  closeHoverColor?: string;
  dragOverColor?: string;
}

/**
 * Options for configuring the useMultiTabs hook.
 */
export interface UseMultiTabsOptions {
  /** localStorage key for persisting tabs. Default: 'drm-multitabs' */
  storageKey?: string;
  /** Default icon for tabs without a resolved icon. Default: 'circle'. Use null to hide icons. */
  defaultIcon?: string | null;
  /** Maximum number of tabs allowed. Default: unlimited */
  maxTabs?: number;
  /**
   * Resolve a custom title for the current location.
   * If provided, this function is called on every location change.
   */
  resolveTitle?: (pathname: string, search: string) => string | null;
  /**
   * Resolve a custom tab model from the current React Router location.
   * This is the main extension point for route-based titles, icons, and
   * metadata.
   */
  resolveTab?: MultiTabResolver;
  /**
   * Return false to prevent a tab from closing.
   * Used by both closeTab() and closeAllTabs().
   */
  onBeforeClose?: (tab: MultiTabItem, context: MultiTabCloseContext) => boolean;
  /** Called when a new tab is added to the current workspace. */
  onTabOpen?: (tab: MultiTabItem) => void;
  /** Called when a tab is removed from the current workspace. */
  onTabClose?: (tab: MultiTabItem) => void;
  /** Called when the active tab changes. */
  onTabChange?: (tab: MultiTabItem) => void;
}

/**
 * Context passed to onBeforeClose() so consumers can decide how to handle
 * individual close actions.
 */
export interface MultiTabCloseContext {
  reason: "close" | "close-all";
  currentTabId: string | null;
  remainingTabs: MultiTabItem[];
}

/**
 * Shared state and actions returned by the React MultiTabs controller.
 */
export interface UseMultiTabsReturn {
  tabs: MultiTabItem[];
  currentTabId: string;
  currentTab: MultiTabItem | null;
  openTab: (tab: MultiTabItem) => void;
  closeTab: (tab: MultiTabItem) => void;
  closeAllTabs: () => void;
  moveTab: (sourceId: string, targetId: string) => void;
  reloadTab: (tab: MultiTabItem) => void;
}

export interface ResolveTabContext {
  /** Existing tab with the same ID, if one already exists. */
  existingTab: MultiTabItem | null;
  /** Default tab generated by the package before applying overrides. */
  defaultTab: MultiTabItem;
}

export type ResolveTabResult = Partial<MultiTabItem> | null | void;

export type MultiTabResolver = (
  location: Location,
  context: ResolveTabContext,
) => ResolveTabResult;
